# Generated by Django 5.1.1 on 2024-09-28 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField()),
                ("duration", models.TimeField()),
                ("description", models.TextField()),
                ("url", models.CharField(max_length=200)),
                ("added", models.DateTimeField(auto_now=True)),
                (
                    "chanel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channel.channel",
                    ),
                ),
            ],
        ),
    ]
