# Generated by Django 5.1.1 on 2024-09-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episode", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="duration",
        ),
    ]
