# Generated by Django 5.1.1 on 2024-09-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episode", "0002_remove_episode_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="chanel",
            new_name="channel",
        ),
    ]
