# Generated by Django 5.1.1 on 2024-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episode", "0003_rename_chanel_episode_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="external_guid",
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
    ]
