# Generated by Django 5.1.1 on 2024-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episode", "0004_episode_external_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="external_guid",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
