# Generated by Django 5.1.1 on 2024-09-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episode", "0006_alter_episode_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="pub_date",
            field=models.DateTimeField(),
        ),
    ]
