# Generated by Django 5.1.1 on 2024-10-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0003_alter_channel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
